version: '2'
services:
  mongodb:
    image: mongo:3.4.9
    ports:
      - "27017:27017"
    volumes:
      - /mongodb:/data/db

  mongo-express:
    image: mongo-express:0.42.2
    ports:
      - "8081:8081"
    links:
      - mongodb:mongo

  rabbitmq:
    image: rabbitmq:3.7.2-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=12345
    logging:
      driver: json-file
      options:
        max-size: "250m"
        max-file: "10"